Fix syntax and install curl for deploy backend.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -233,6 +233,12 @@ jobs:
       - attach_workspace:
           at: my_workspace
       - run:
+          name: Install system dependencies
+          command: |
+            pip install awscli
+            apk add --update curl tar
+            apk add npm
+      - run:
           name: Get backend url
           command: |
             export BACKEND_IP=$(aws ec2 describe-instances \
@@ -240,15 +246,9 @@ jobs:
             --filter Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} \
             --output text)
             export API_URL="http://${BACKEND_IP}:3030"
-            echo "${API_URL}"
+            echo "API_URL = ${API_URL}"
             echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
             cat frontend/.env
-      - run:
-          name: Install system dependencies
-          command: |
-            pip install awscli
-            apk add --update curl tar
-            apk add npm
       - run:
           name: Deploy frontend objects
           command: |
@@ -299,108 +299,108 @@ jobs:
       - destroy-environment
       - revert-migrations
 
-  smoke-test:
-    docker:
-      - image: python:3.8-alpine3.12
-    steps:
-      - checkout
-      - attach_workspace:
-          at: ~/
-      - run:
-          name: Install awscli
-          command: |
-            pip install awscli
-      - run:
-          name: Install curl
-          command: |
-            apk add --update curl
-      - run:
-          name: Backend smoke test.
-          command: |
-            # Fetch and prepare the BACKEND_IP env var
-            BACKEND_IP=$(aws ec2 describe-instances \
-            --query 'Reservations[*].Instances[*].PublicIpAddress' \
-            --filter Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} \
-            --output text)
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo $(BACKEND_IP)
-            echo backend-${CIRCLE_WORKFLOW_ID:0:7}
-            echo "${API_URL}"
-            if curl "${API_URL}/api/status" | grep "ok";
-            then
-                echo "API is running."
-                exit 0
-            else
-                echo "API is down."
-                exit 1
-            fi
-      - run:
-          name: Frontend smoke test.
-          command: |
-            FRONTEND_URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com"
-            echo ${FRONTEND_URL}
-            if curl "${FRONTEND_URL}" | grep "Welcome"
-            then
-                return 1
-            else
-                echo "Front-end smoke test failed"
-                return 1
-            fi
-      - destroy-environment
-      - revert-migrations
-
-  cloudfront-update:
-    docker:
-    - image: amazon/aws-cli
-    steps:
-      - checkout
-      - run:
-          name: Save old workflow ID to bucket
-          command: |
-            export OldWorkflowID=$(aws cloudformation \
-            list-exports --query "Exports[?Name==\'WorkflowID\'].Value \
-            --no-paginate --output text)
-            echo "OldWorkFlowID: $OldWorkflowID"
-            curl https://kvdb.io/M6ufhpdLz3tp23wmyD76YY/OldWorkFlowID -d "${OldWorkflowID}"
-      - run:
-          name: Update cloudfront distribution
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/cloudfront.yml \
-              --stack-name InitialStack \
-              --parameter-overrides WorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7}" \
-      # Here's where you will add some code to rollback on failure
-      - destroy-environment
-      - revert-migrations
-
-cleanup:
-    docker:
-      - image: amazon/aws-cli
-    steps:
-      - checkout
-      - run:
-          name: Get old stack workflow id
-          command: |
-            export OldStacks=($(aws cloudformation list-stacks \
-            --query "StackSummaries[*].StackName" \
-            --stack-status-filter CREATE_COMPLETE --no-pagination \
-            --output text))
-            echo Stack Names: "${OldStacks[@]}"
-            export OldWorkflowID=$(curl --insecure https://kvdb.io/M6ufhpdLz3tp23wmyD76YY/OldWorkFlowID)
-            echo OldWorkflowID=$OldWorkflowID
-      - run:
-          name: Remove old stacks and files
-          command: |
-            export OldWorkflowID=$(curl --insecure https://kvdb.io/M6ufhpdLz3tp23wmyD76YY/OldWorkFlowID)
-            echo OldWorkflowID=$OldWorkflowID
-            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-            then
-              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
-            aws cloudformation delete-stack \
-              --stack-name udapeople-backend-${OldWorkflowID}
-            aws cloudformation delete-stack \
-              --stack-name udapeople-frontend-${OldWorkflowID}
-            fi
+#  smoke-test:
+#    docker:
+#      - image: python:3.8-alpine3.12
+#    steps:
+#      - checkout
+#      - attach_workspace:
+#          at: ~/
+#      - run:
+#          name: Install awscli
+#          command: |
+#            pip install awscli
+#      - run:
+#          name: Install curl
+#          command: |
+#            apk add --update curl
+#      - run:
+#          name: Backend smoke test.
+#          command: |
+#            # Fetch and prepare the BACKEND_IP env var
+#            BACKEND_IP=$(aws ec2 describe-instances \
+#            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+#            --filter Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} \
+#            --output text)
+#            export API_URL="http://${BACKEND_IP}:3030"
+#            echo $(BACKEND_IP)
+#            echo backend-${CIRCLE_WORKFLOW_ID:0:7}
+#            echo "${API_URL}"
+#            if curl "${API_URL}/api/status" | grep "ok";
+#            then
+#                echo "API is running."
+#                exit 0
+#            else
+#                echo "API is down."
+#                exit 1
+#            fi
+#      - run:
+#          name: Frontend smoke test.
+#          command: |
+#            FRONTEND_URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com"
+#            echo ${FRONTEND_URL}
+#            if curl "${FRONTEND_URL}" | grep "Welcome"
+#            then
+#                return 1
+#            else
+#                echo "Front-end smoke test failed"
+#                return 1
+#            fi
+#      - destroy-environment
+#      - revert-migrations
+#
+#  cloudfront-update:
+#    docker:
+#    - image: amazon/aws-cli
+#    steps:
+#      - checkout
+#      - run:
+#          name: Save old workflow ID to bucket
+#          command: |
+#            export OldWorkflowID=$(aws cloudformation \
+#            list-exports --query "Exports[?Name==\'WorkflowID\'].Value \
+#            --no-paginate --output text)
+#            echo "OldWorkFlowID: $OldWorkflowID"
+#            curl https://kvdb.io/M6ufhpdLz3tp23wmyD76YY/OldWorkFlowID -d "${OldWorkflowID}"
+#      - run:
+#          name: Update cloudfront distribution
+#          command: |
+#            aws cloudformation deploy \
+#              --template-file .circleci/files/cloudfront.yml \
+#              --stack-name InitialStack \
+#              --parameter-overrides WorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7}" \
+#      # Here's where you will add some code to rollback on failure
+#      - destroy-environment
+#      - revert-migrations
+#
+#cleanup:
+#    docker:
+#      - image: amazon/aws-cli
+#    steps:
+#      - checkout
+#      - run:
+#          name: Get old stack workflow id
+#          command: |
+#            export OldStacks=($(aws cloudformation list-stacks \
+#            --query "StackSummaries[*].StackName" \
+#            --stack-status-filter CREATE_COMPLETE --no-pagination \
+#            --output text))
+#            echo Stack Names: "${OldStacks[@]}"
+#            export OldWorkflowID=$(curl --insecure https://kvdb.io/M6ufhpdLz3tp23wmyD76YY/OldWorkFlowID)
+#            echo OldWorkflowID=$OldWorkflowID
+#      - run:
+#          name: Remove old stacks and files
+#          command: |
+#            export OldWorkflowID=$(curl --insecure https://kvdb.io/M6ufhpdLz3tp23wmyD76YY/OldWorkFlowID)
+#            echo OldWorkflowID=$OldWorkflowID
+#            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+#            then
+#              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+#            aws cloudformation delete-stack \
+#              --stack-name udapeople-backend-${OldWorkflowID}
+#            aws cloudformation delete-stack \
+#              --stack-name udapeople-frontend-${OldWorkflowID}
+#            fi
 
 
 # Orchestrate our job run sequence
@@ -430,10 +430,10 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
-      - smoke-test:
-          requires: [deploy-backend, deploy-frontend]
-      - cloudfront-update:
-          requires: [smoke-test]
+#      - smoke-test:
+#          requires: [deploy-backend, deploy-frontend]
+#      - cloudfront-update:
+#          requires: [smoke-test]
 #      - cleanup:
 #          requires: [cloudfron-update]
 
