Run smoke tests.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -294,63 +294,63 @@ jobs:
             cd ..
             tar -C backend -czvf artifact.tar.gz .
             mv artifact.tar.gz project/.circleci/ansible/roles/deploy/artifacts/artifact.tar.gz
-            cd ../
+            cd .circleci/ansible
             echo "Contents  of the inventory.txt file is -------"
             cat inventory.txt
             ansible-playbook -i inventory.txt deploy-backend.yml
       - destroy-environment
       - revert-migrations
 
-#  smoke-test:
-#    docker:
-#      - image: python:3.8-alpine3.12
-#    steps:
-#      - checkout
-#      - attach_workspace:
-#          at: ~/
-#      - run:
-#          name: Install awscli
-#          command: |
-#            pip install awscli
-#      - run:
-#          name: Install curl
-#          command: |
-#            apk add --update curl
-#      - run:
-#          name: Backend smoke test.
-#          command: |
-#            # Fetch and prepare the BACKEND_IP env var
-#            BACKEND_IP=$(aws ec2 describe-instances \
-#            --query 'Reservations[*].Instances[*].PublicIpAddress' \
-#            --filter Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} \
-#            --output text)
-#            export API_URL="http://${BACKEND_IP}:3030"
-#            echo $(BACKEND_IP)
-#            echo backend-${CIRCLE_WORKFLOW_ID:0:7}
-#            echo "${API_URL}"
-#            if curl "${API_URL}/api/status" | grep "ok";
-#            then
-#                echo "API is running."
-#                exit 0
-#            else
-#                echo "API is down."
-#                exit 1
-#            fi
-#      - run:
-#          name: Frontend smoke test.
-#          command: |
-#            FRONTEND_URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com"
-#            echo ${FRONTEND_URL}
-#            if curl "${FRONTEND_URL}" | grep "Welcome"
-#            then
-#                return 1
-#            else
-#                echo "Front-end smoke test failed"
-#                return 1
-#            fi
-#      - destroy-environment
-#      - revert-migrations
-#
+  smoke-test:
+    docker:
+      - image: python:3.8-alpine3.12
+    steps:
+      - checkout
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Install awscli
+          command: |
+            pip install awscli
+      - run:
+          name: Install curl
+          command: |
+            apk add --update curl
+      - run:
+          name: Backend smoke test.
+          command: |
+            # Fetch and prepare the BACKEND_IP env var
+            BACKEND_IP=$(aws ec2 describe-instances \
+              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo $(BACKEND_IP)
+            echo backend-${CIRCLE_WORKFLOW_ID:0:7}
+            echo "${API_URL}"
+            if curl ${API_URL}/api/status | grep "ok";
+            then
+                echo "API is running."
+                exit 0
+            else
+                echo "API is down."
+                exit 1
+            fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+            FRONTEND_URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com"
+            echo ${FRONTEND_URL}
+            if curl "${FRONTEND_URL}" | grep "Welcome"
+            then
+                return 1
+            else
+                echo "Front-end smoke test failed"
+                return 1
+            fi
+      - destroy-environment
+      - revert-migrations
+
 #  cloudfront-update:
 #    docker:
 #    - image: amazon/aws-cli
@@ -432,8 +432,8 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
-#      - smoke-test:
-#          requires: [deploy-backend, deploy-frontend]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
 #      - cloudfront-update:
 #          requires: [smoke-test]
 #      - cleanup:
